---

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introducción a la Estadística

La Estadística es la ciencia que se encarga de observar, agrupar, clasificar y organizar datos para su posterior interpretación, análisis y toma de decisiones. El Universo está compuesto de infinidad de datos cuantitativos y cualitativos, desde las diferentes disciplinas pueden interpretarse con el fin de comprender profundamente todos los fenómenos, pero la estadística puede abarcar, sin atreverse a reemplazar, las diferentes esferas del conocimiento para darle soporte a los descubrimientos.

> Los métodos estadísticos están enfocados para tratar con la complejidad de la realidad, no obstante es importante que aquel que aplique la estadística comprenda profundamente, tanto los fenómenos a estudiar en su movimiento, como las herramientas propicias y su correcta interpretación. En la actualidad, se ha tratado la estadística como conjunto de métodos complementarios a la disciplina original del investigador, llevando a que éstos menosprecien la seriedad que amerita la comprensión de todo su universo; a su vez la estadística ha sido empleada con fines pseudocientíficos para justificar comportamientos sociales, leyes jurídicas y económicas o publicación de fármacos ineficientes o peligrosos. 

## Generalidad y Oportunidad

Cuando se escucha la palabra Estadística, la primera asociación es con la **oficialidad**, con las estadísticas del Estado: índices de pobreza, desempleo, violencia, entre otras. Si bien dichas cifras en ocasiones no reflejan la realidad de un país, esto no quiere decir que los métodos estadísticos o la Estadística en general es equívoca, pues la ciencia no es neutral, es decir, son los seres humanos quienes desarrollan técnicas y hacen descubrimientos en medio de relaciones sociales que son reflejo de la dinámica económica actual, por tanto los intereses de grupos de personas se ven reflejados en el desarrollo de la ciencia, en su uso y sus objetivos.

> Es menester de los investigadores, que realmente respetan la ciencia, hacer una valoración epistemológica de su qué hacer científico, es decir, la motivación del **para qué** de la investigación, pues el papel de la ciencia debe estar enfocada en buscar la verdad tal y como es, sin importar si conviene o no a un grupo en particular.

## Tipos de Estadística

La Estadística presenta dos etapas para el estudio de los datos, la estadística descriptiva y la analítica. La *estadística descriptiva* o *deductiva* comprende todo el conjunto de herramientas para organizar, clasificar y evidenciar aspectos característicos de los datos, que sirve para efectuar comparaciones sin pretender sacar conclusiones, es simplemente apreciativo y el primer paso para realizar hipótesis. Estas descripciones se logran a través de la construcción de tablas, gráficas, cuadros, cálculos de promedios, varianzas y proporciones.

La *estadística analítica* o *inferencial* busca dar explicaciones al comportamiento particular de un conjunto de observaciones, probar significación o validez de las hipótesis planteadas e intenta descubrir las causas que originan dichos comportamientos. Con la inferencia se puede hacer conclusiones contundentes sobre las comparaciones o el modelamiento de las muestras.

Una parte fundamental de la estadística es la que comprende el *muestreo*, que trata de las técnicas para la determinación de tamaños de muestra de acuerdo al tipo de población de estudio, a su vez el muestreo comprende las formas de recolección de los datos, buscando completa aleatorización del proceso para evitar errores o sesgos en el desarrollo de la investigación.

> Sin muestras no es posible hacer **estadística descriptiva**, sin los datos organizados y bien descritos no es posible hacer **inferencias** sobre los resultados y sin comprender las técnicas e interpretar bien la estadística inferencial no es posible utilizar correctamente las técnicas de **muestreo**.

La estadística no es un proceso lineal, más bien, como toda ciencia, tiene proceso en espiral, y la principal forma de hacer buena estadística es comprender profundamente sus conceptos, la correcta interpretación de los resultados.

## Finalidad de la Estadística

El profesor Ciro Martínez en su libro *“Estadística y Muestreo”* presenta algunos aspectos para los cuales la estadística tiene importancia.

-	**Conocer la realidad de una observación o fenómeno.** Cuando se cuantifica un fenómeno se conoce su situación actual. Los fenómenos se transforman en el tiempo, pero no al unísono; si queremos obtener la información acerca de la producción de ladrillo, el seguimiento en el tiempo se puede realizar por horas, días o semanas para evaluar los costos-beneficios de la producción, por otra parte, si queremos evaluar las condiciones minerales de la caliza para la producción de mármol, el seguimiento en el tiempo toma dimensiones mucho más amplias, asegurando que los posibles cambios que surjan en la tierra tomarán décadas o siglos.

-	**Determinar lo típico o normal de esa observación.** Cuando obtenemos una cantidad considerable de registros sobre el fenómeno a estudiar, el cálculo del promedio orienta al investigador cuantitativamente cómo es su comportamiento. Al agregar un aditivo al concreto para mejorar su plasticidad y reducir el tiempo para que sufra deformación, el promedio del coeficiente de flujo plástico es una forma de determinar el comportamiento de la mezcla realizada; pero este valor típico no quiere decir que todas las muestras utilizadas presenten el mismo coeficiente, posiblemente algunos presenten coeficientes bajos y otros altos.

-	**Determinar los cambios que presenta el fenómeno.** Cualquier fenómeno presenta variaciones en el tiempo, por otra parte los fenómenos también son afectados por diferentes factores, pero esto requiere de observaciones continuas para poder determinar la magnitud del cambio. El cálculo de las medidas de dispersión, como la varianza sirven para determinar el grado de variabilidad de las muestras con respecto al valor típico. Siguiendo con el ejemplo anterior, cuando se calcula la desviación estándar del coeficiente de flujo plástico, se puede determinar los límites de los valores del coeficiente que son atípicos, si la desviación es grande quiere decir que los datos están más dispersos, lo que puede significar errores en la medición o en los instrumentos.

-	**Relacionar dos o más fenómenos.** Se puede determinar si existe una relación válida entre dos o más características de una misma observación a partir de la correlación, por ejemplo la relación que tiene la evapotranspiración de la tierra respecto a la temperatura ambiente.

-	**Determinar las causas que originan un fenómeno.** Los cambios que se observan en un fenómeno pueden tener una o varias causas de origen. El aumento del tiempo de secado del concreto puede ser causado por bajas temperaturas, niveles altos de humedad relativa o el aumento de las precipitaciones en la zona.

-	**Hacer estimativos sobre el comportamiento futuro del fenómeno.** En las obras construidas, y en general en los bienes que se producen, se requiere estimar la durabilidad del producto, pues determinará su valor comercial y el tiempo de uso.

-	**Obtener conclusiones de un grupo menor (muestra), para hacerlas extensivas a un grupo mayor (población).** Al realizar mediciones de una muestra, cuyo tamaño debe ser el óptimo deseado, los resultados obtenidos pueden ser considerados como el comportamiento que se obtendrá si se hubiera trabajado con todos los elementos que constituyen la población, de la cual se extrajo la muestra.



