---
title: "Curso R y RStudio - EAFIT"
author: "Cristian Santa"
date: "Marzo de 2019"
output:
 rmdformats::readthedown:
    df_print: paged
    code_folding: show
    highlight: tango
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introducción al manejo de datos con R y RStudio

Curso ofertado para el Centro de Educación Continua de la universidad EAFIT

### Objetivo de estudio

Aprendizaje del lenguaje R y pensamiento algorítmico para el análisis de datos					

### Dirigido A

Personas con conocimientos básicos de programación, que deseen aumentar su versatilidad en el análisis y tratamiento de datos, sea para objeto de investigación o de análisis y mejoramiento de procesos productivos-empresariales.					

### Objetivo del programa

Introducir al estudiante al manejo del software estadístico más usado en investigación, R-Project, y su interfaz R-Studio, para el manejo de estructuras de datos, gráficos y simulación.					

## Contenido

| **Clase** |                                 **Descripción**                                |
|:---------:|--------------------------------------------------------------------------------|
|  <a href="./Clase01/Clase01.html">C_01</a>  | Introducción a R-Project y R-Studio. Instalación y configuración del software. |
|  <a href="./Clase02/Clase02.html">C_02</a>  | Estructuras de datos, tipos y clases de objetos. Vectores y matrices.       |
|  <a href="./Clase03/Clase03.html">C_03</a>  | Condicionales y ciclos. Secuencias. Número aleatorios.                         |
|  <a href="./Clase04/Clase04.html">C_04</a>  | Funciones en R y uso de librerías.                                             |
|  <a href="./Clase05/Clase05.html">C_05</a>  | Gráficos básicos.                                                              |
|  <a href="./Clase06/Clase06.html">C_06</a>  | Gráficos avanzados.                                                            |
|  <a href="./Clase07/Clase07.html">C_07</a>  | Expresiones Regulares.                                                         |
|  <a href="./Clase08/Clase08.html">C_08</a>  | Manejo de bases de datos.                                                      |
|  <a href="./Clase09/Clase09.html">C_09</a>  | Manejo de datos temporales y operaciones con tiempos.                          |
|  <a href="./Clase10/Clase10.html">C_10</a>  | Trabajo práctico.                                                              |
|  <a href="./Clase11/Clase11.html">C_11</a>  | Introducción al análisis estadístico con R.                                    |
|  <a href="./Clase12/Clase12.html">C_12</a>  | Análisis estadístico con R (II).                                               |

## Docente

**Cristian Santa Escobar**: Estadístico con ocho años de experiencia en análisis y clasificación de datos, planificación de diseños experimentales, muestreo, modelación estadística y programación avanzada en R-Project. Especialista en Data Science de la Universidad John Hopkings y Magíster en Ciencias Estadísticas de la Universidad Nacional sede Medellín. Su área de investigación se centra en los análisis multivariados con variables categóricas y los modelos de estructuras de covarianza.

### Contacto

**e-mail:** cdsantae@gmail.com <br>
Para enviar correos se solicita anteponer en el asunto **[EAFIT]**.


