---
title: "Curso R y RStudio - EAFIT"
author: "Cristian Santa"
date: "Marzo de 2019"
output:
 rmdformats::readthedown:
    df_print: paged
    code_folding: show
    highlight: tango
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introducción al manejo de datos con R y RStudio

Curso ofertado para el Centro de Educación Continua de la universidad EAFIT

### Objetivo de estudio

Aprendizaje del lenguaje R y pensamiento algorítmico para el análisis de datos					

### Dirigido A

Personas con conocimientos básicos de programación, que deseen aumentar su versatilidad en el análisis y tratamiento de datos, sea para objeto de investigación o de análisis y mejoramiento de procesos productivos-empresariales.					

### Objetivo del programa

Introducir al estudiante al manejo del software estadístico más usado en investigación, R-Project, y su interfaz R-Studio, para el manejo de estructuras de datos, gráficos y simulación.					

### Contenido

| **Clase** |                                 **Descripción**                                |
|:---------:|--------------------------------------------------------------------------------|
|  <a href="EAFIT/Clase01/Clase01.html">Clase 01</a>  | Instalación y configuración del software. Introducción a R-Project y R-Studio. |
|  <a href="EAFIT/Clase02/Clase02.html">Clase 02</a>  | Vectores y matrices. Estructuras de datos, tipos y clases de objetos.          |
|  <a href="EAFIT/Clase03/Clase03.html" disabled="disabled">Clase 03</a>  | Condicionales y ciclos. Secuencias.                                            |
|  <a href="EAFIT/Clase04/Clase04.html" disabled="disabled">Clase 04</a>  | Funciones en R.                                                                |
|  <a href="EAFIT/Clase05/Clase05.html" disabled="disabled">Clase 05</a>  | Orientación a objetos.                                                         |
|  <a href="EAFIT/Clase06/Clase06.html" disabled="disabled">Clase 06</a>  | Gráficos básicos.                                                              |
|  <a href="EAFIT/Clase07/Clase07.html" disabled="disabled">Clase 07</a>  | Uso de librerías.                                                              |
|  <a href="EAFIT/Clase08/Clase08.html" disabled="disabled">Clase 08</a>  | Gráficos avanzados.                                                            |
|  <a href="EAFIT/Clase09/Clase09.html" disabled="disabled">Clase 09</a>  | Expresiones regulares.                                                         |
|  <a href="EAFIT/Clase10/Clase10.html" disabled="disabled">Clase 10</a>  | Manejo de bases de datos.                                                      |
|  <a href="EAFIT/Clase11/Clase11.html" disabled="disabled">Clase 11</a>  | Manejo de datos temporales.                                                    |
|  <a href="EAFIT/Clase12/Clase12.html" disabled="disabled">Clase 12</a>  | Introducción al análisis estadístico con R                                     |

### Docente

**Cristian Santa Escobar**: Estadístico con ocho años de experiencia en análisis y clasificación de datos, planificación de diseños experimentales, muestreo, modelación estadística y programación avanzada en R-Project. Especialista en Data Science de la Universidad John Hopkings y Magíster en Ciencias Estadísticas de la Universidad Nacional sede Medellín. Su área de investigación se centra en los análisis multivariados con variables categóricas y los modelos de estructuras de covarianza.

### Contacto

**e-mail:** cdsantae@gmail.com
Para enviar correos se solicita anteponer en el asunto **[EAFIT]**.


