<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Intervalos de Confianza para dos grupos</title>

<script src="site_libs/header-attrs-2.6/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


<link rel="stylesheet" href="bootstrap.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Investigación II</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="glyphicon glyphicon glyphicon glyphicon-stats"></span>
     
    Descriptiva
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="D_concept.html">Conceptos</a>
    </li>
    <li>
      <a href="D_graph.html">Gráficos</a>
    </li>
    <li>
      <a href="D_stat.html">Estadísticos</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fas fa-dice"></span>
     
    Probabilidad
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="P_intro.html">Introducción</a>
    </li>
    <li>
      <a href="P_prob.html">Probabilidad</a>
    </li>
    <li>
      <a href="P_dist.html">Distribuciones</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="glyphicon glyphicon glyphicon glyphicon-random"></span>
     
    Inferencia
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="I_dist.html">Distribuciones Muestrales</a>
    </li>
    <li>
      <a href="I_ic1.html">IC para un parámetro</a>
    </li>
    <li>
      <a href="I_ic2.html">IC para diferencias</a>
    </li>
    <li>
      <a href="I_ph1.html">PH para un parámetro</a>
    </li>
    <li>
      <a href="I_ph2.html">PH para diferencias</a>
    </li>
    <li>
      <a href="I_et2.html">Potencia</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="glyphicon glyphicon glyphicon glyphicon-equalizer"></span>
     
    Muestreo
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="M_effect.html">Sobre el efecto</a>
    </li>
    <li>
      <a href="M_MAS.html">MAS</a>
    </li>
    <li>
      <a href="M_MAE.html">MAE</a>
    </li>
    <li>
      <a href="M_Cluster.html">Cluster</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fas fa-code"></span>
     
    R-Project
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Rinstall.html">Instalación</a>
    </li>
    <li>
      <a href="IntroR.html">Introducción</a>
    </li>
    <li>
      <a href="FunsR.html">Funciones y Paquetes</a>
    </li>
    <li>
      <a href="RData.html">Manejo de Datos</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="mailto:cdavid.santa@udea.edu.co">
    <span class="glyphicon glyphicon glyphicon glyphicon-envelope"></span>
     
  </a>
</li>
<li>
  <a href="https://cdsantae.github.io">
    <span class="fas fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Intervalos de Confianza para dos grupos</h1>

</div>


<hr>
<div id="inferencia-comparación-de-grupos" class="section level2">
<h2>Inferencia comparación de grupos</h2>
<p>Hasta ahora se ha realizado estimaciones para un parámetros. Ahora, el interés es comparar dos grupos, es decir, comparar una característica común pero que se diferencian en dos estados distintos y que no existen otras condiciones adicionales que diferencien las dos muestras.</p>
<p>Para estos casos se presentan dos situaciones, que las muestras sean <strong>independientes</strong> o que las muestras sean <strong>pareadas</strong>, es decir, que es el seguimiento de un solo individuo en el cambio de estado (tiempo, área, condición).</p>
<p><img src="I_ic2_files/figure-html/unnamed-chunk-1-1.png" width="1200" style="display: block; margin: auto;" /></p>
<p>Dada estas situaciones entonces surge la pregunta ¿Existe diferencia significativa entre los dos grupos? Para responder esta pregunta tenemos dos procedimientos para llegar a la respuesta:</p>
<ul>
<li><strong>Intervalos de confianza</strong></li>
<li><strong>Pruebas de hipótesis</strong></li>
</ul>
<hr>
</div>
<div id="intervalo-de-confianza-para-la-diferencia-de-proporciones" class="section level2">
<h2>Intervalo de confianza para la diferencia de proporciones</h2>
<p>A menudo se tiene interés en conocer la magnitud de la diferencia entre las proporciones de dos poblaciones. Es posible que se quiera comparar, por ejemplo, entre hombres y mujeres, dos grupos de edades, dos grupos socioeconómicos o dos grupos de diagnóstico con respecto a la proporción que posee alguna característica de interés.</p>
<p>Se tienen <span class="math inline">\(X_1,\dots,X_n\)</span> y <span class="math inline">\(Y_1,\dots,Y_n\)</span> dos muestras aleatorias cada una pertenecientes a una distribución binomial <span class="math inline">\(X\sim bin(n_1,p_1)\)</span> y <span class="math inline">\(Y\sim bin(n_2,p_2)\)</span>. Un estimador puntual insesgado de la diferencia entre dos proporciones de las poblaciones se obtiene al calcular la diferencia de las proporciones de las muestras <span class="math inline">\(\hat{p_1}-\hat{p_2}\)</span>. Tal como se ha visto, cuando <span class="math inline">\(n_1\)</span> <span class="math inline">\(n_2\)</span> son de <strong>gran tamaño</strong> y las proporciones de la población no están muy cerca de <span class="math inline">\(0\)</span> o de <span class="math inline">\(1\)</span>, es posible aplicar el <strong>Teorema Central del Limite</strong> y utilizar la teoría de la distribución normal para obtener los intervalos de confianza.</p>
<p>El error estándar de la estimación se calcula mediante la siguiente formula:</p>
<p><span class="math display">\[\Large\hat{\sigma}_{\hat{p_1}-\hat{p_2}}=\sqrt{\frac{\hat{p_1}(1-\hat{p_1})}{n_1}+\frac{\hat{p_2}(1-\hat{p_2})}{n_2}}\]</span></p>
<p>Entonces un intervalo de confianza al <span class="math inline">\(100(1-\alpha)\%\)</span> para <span class="math inline">\(p_1-p_2\)</span> se obtiene de:</p>
<p><span class="math display">\[(\hat{p_1}-\hat{p_2})\,\pm\,Z_{1-\alpha/2}\sqrt{\frac{\hat{p_1}(1-\hat{p_1})}{n_1}+\frac{\hat{p_2}(1-\hat{p_2})}{n_2}}\]</span></p>
<blockquote>
<p>Entonces cuando el intervalo contenga el valor <span class="math inline">\(0\)</span> significa que los grupos son <strong>estadística mente iguales</strong>, eso se debe a: <span class="math display">\[p_1 - p_2 = 0 \quad \rightarrow \quad p_1=p_2\]</span></p>
</blockquote>
<blockquote>
Aronow y Kronzon identificaron los factores de riesgo coronado entre hombres y mujeres en una clínica de cuidados de la salud a largo plazo. De los 215 individuos negros, 58 tienen <em>diabetes mellitus</em> al igual que 217 individuos blancos de 1140. Elabore un intervalo de confianza de 90 por ciento de confianza para la diferencia entre las proporciones de las dos poblaciones. <br> Con la información suministrada podemos construir una tabla de contingencia de la siguiente manera: <br>
<table class="table table-striped table-hover">
<thead>
<tr>
<th>
</th>
<th colspan="2">
Diabetes
</th>
<th>
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
Si
</td>
<td>
No
</td>
<td>
Total
</td>
</tr>
<tr>
<td>
Negros
</td>
<td>
58
</td>
<td>
157
</td>
<td>
215
</td>
</tr>
<tr>
<td>
Blancos
</td>
<td>
217
</td>
<td>
923
</td>
<td>
1140
</td>
</tr>
</tbody>
</table>
<p><br> Como el interés es comparar entre negros y blancos por la presencia de diabetes, entonces se tiene que <span class="math inline">\(p_1=58/215\)</span> y <span class="math inline">\(p_2=217/1140\)</span>. Así el intervalo de confianza al 90% está dado por: <span class="math display">\[\begin{align*}
(\hat{p_1}-\hat{p_2})\,\pm&amp;\,Z_{1-\alpha/2}\sqrt{\frac{\hat{p_1}(1-\hat{p_1})}{n_1}+\frac{\hat{p_2}(1-\hat{p_2})}{n_2}}\\
\left(\frac{58}{215}-\frac{217}{1140}\right)\,\pm&amp;\,Z_{0.95}\sqrt{\frac{(58/157)({157/215})}{215}+\frac{(217/1140)(923/1140)}{1140}}\\
\end{align*}\]</span> <span class="math display">\[(-0.02608\,;\,0.13275)\]</span> El intervalo de confianza para la diferencia de proporciones contiene el 0% por lo tanto, no existe diferencias para la diabetes entre negros y blancos con una confianza del 90%.</p>
</blockquote>
<hr>
</div>
<div id="intervalo-de-confianza-para-la-diferencia-de-medias" class="section level2">
<h2>Intervalo de confianza para la diferencia de medias</h2>
<p>El procedimiento de comparar grupos a través de los medias estimadas, similar a estimar un solo parámetro, requiere de una serie de evaluaciones para seleccionar el método correcto de acuerdo al comportamiento de los datos.</p>
<ol style="list-style-type: decimal">
<li>Verificar que los datos distribuyen normal o no.</li>
<li>Verificar si los tamaños de cada muestra son suficientemente grandes.</li>
<li>Verificar si las varianzas de cada muestra son iguales o no.</li>
<li>Seleccionar el método de estimación.</li>
</ol>
<hr>
<div id="verificación-de-la-normalidad" class="section level3">
<h3>Verificación de la normalidad</h3>
<p>El primer paso se realiza a través de los métodos de <strong>Pruebas de Hipótesis</strong> que se abordará en el siguiente capítulo, no obstante de acuerdo a las propiedades de la <strong>Distribución Normal</strong> se puede realizar una inspección gráfica.</p>
<p><img src="I_ic2_files/figure-html/unnamed-chunk-2-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>Estos tres gráficos nos ayudarán para explorar el comportamiento de los datos y se pueden combinar con los gráficos de las distribuciones teóricas para evaluar qué tanto se parecen.</p>
<p>El primer gráfico se llama <strong>Gráfico de Densidad</strong>, muestra cómo es la distribución empírica de probabilidad, a diferencia del <em>Histograma</em> es una buena aproximación de las distribuciones continuas.</p>
<p>El segundo gráfico se llama <strong>Gráfico Densidad Acumulada Empírica</strong>, este gráfico es muy útil cuando se compara con <em>La densidad acumulada</em> de las distribuciones teóricas. Además, el gráfico muestra el salto de cada muestra en la función de densidad acumulada empírica.</p>
<p>El tercer gráfico se llama <strong>Gráfico de Comparación de Cuantiles</strong>, contrasta las muestras con los cuantiles de la distribución teórica. La ventaja de este gráfico es que dibuja una recta en la cual se <em>espera</em> que el conjunto de datos se ajuste, además dibuja bandas de confianza para mostrar hasta dónde se puede considerar que los puntos se ajustan a la recta.</p>
<p><img src="I_ic2_files/figure-html/unnamed-chunk-3-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>La idea de este gráfico es que los puntos estén muy cercanos a la recta y entre los límites de confianza. Hay que tener cuidado en los extremos de las muestras, ya que algunos puntos pueden salir de las bandas pero esto no significa que no tengan la distribución que se está evaluando; si la mayoría de los puntos están ajustados a la recta y son muy pocos datos <strong>en los extremos</strong> que salen de las bandas, se puede considerar un buen ajuste.</p>
<hr>
</div>
<div id="pruebas-de-igualdad-de-varianza" class="section level3">
<h3>Pruebas de igualdad de Varianza</h3>
<p>Otro paso importante es verificar si las varianzas de ambos grupos son iguales o no, esto es importante porque la intención de la comparación de grupos a partir de la diferencia de promedios solamente debe comparar un factor o grupo que diferencia las muestras. La presencia de variabilidad excesiva en una de las muestras indicaría que existe otra condición no analizada que puede afectar la comparación, sin embargo, es posible controlar este problema estimando una variación conjunta entre los dos grupos.</p>
<p>La comparación de dos varianzas se realiza a través de su razón, <span class="math inline">\(\sigma_1/\sigma_2\)</span> si las varianzas son iguales entonces la razón será <span class="math inline">\(1\)</span>. Por lo general, las variancias de las poblaciones son desconocidas y, en consecuencia, toda comparación que haga deberá basarse en las variancias de las muestras. Basado en el Teorema Central del Límite se puede demostrar que la razón de dos varianzas tiene una distribución <strong>F de Snedecor</strong>. Entonces un intervalo de confianza para la razón de varianzas está dado por:</p>
<p><span class="math display">\[F_{(\alpha/2,n_1-1,n_2-1)}&lt;\cfrac{S^2_1/\sigma^2_2}{S^2_2/\sigma^2_2}&lt;F_{(1-\alpha/2,n_1-1,n_2-1)}\\\\
F_{(\alpha/2,n_1-1,n_2-1)}&lt;\cfrac{S^2_1}{S^2_2}\times\cfrac{\sigma^2_2}{\sigma^2_1}&lt;F_{(1-\alpha/2,n_1-1,n_2-1)}\\\\
\cfrac{F_{(\alpha/2,n_1-1,n_2-1)}}{S^2_1/S^2_2}&lt;\cfrac{\sigma^2_2}{\sigma^2_1}&lt;\cfrac{F_{(1-\alpha/2,n_1-1,n_2-1)}}{S^2_1/S^2_2}\\\\
\cfrac{S^2_1/S^2_2}{F_{(\alpha/2,n_1-1,n_2-1)}}&gt;\cfrac{\sigma^2_1}{\sigma^2_2}&gt;\cfrac{S^2_1/S^2_2}{F_{(1-\alpha/2,n_1-1,n_2-1)}}\]</span></p>
<p>Un intervalo al <span class="math inline">\(100(1-\alpha)\%\)</span> para <span class="math inline">\(\sigma^2_1/\sigma^2_2\)</span> está dado por:</p>
<p><span class="math display">\[\cfrac{S^2_1/S^2_2}{F_{(1-\alpha/2,n_1-1,n_2-1)}}&lt;\cfrac{\sigma^2_1}{\sigma^2_2}&lt;\cfrac{S^2_1/S^2_2}{F_{(\alpha/2,n_1-1,n_2-1)}}\]</span></p>
<p><img src="I_ic2_files/figure-html/unnamed-chunk-4-1.png" width="700" style="display: block; margin: auto;" /></p>
<p>En el primer gráfico se evidencia cómo el parámetro <span class="math inline">\(d_2\)</span> determina la altura de la densidad cuando el parámetro <span class="math inline">\(d_1\)</span> está fijo, mientras que en el segundo se ve cómo el parámetro <span class="math inline">\(d_1\)</span> mueve la distribución en el eje <span class="math inline">\(x\)</span> de forma positiva cuando el parámetro <span class="math inline">\(d_2\)</span> está fijo.</p>
<p><img src="I_ic2_files/figure-html/unnamed-chunk-5-1.png" width="700" style="display: block; margin: auto;" /></p>
<p>Cuando los parámetros de la distribución son iguales se nota que para valores <span class="math inline">\(&lt;3\)</span> la distribución tiene tendencia exponencial, y aparece de forma notable la varianza con parámetros <span class="math inline">\(d1=d2\geq4\)</span>. Por otra parte, si ambos parámetros son muy grandes, en el límite la distribución se transforma en una distribución degenerada en <span class="math inline">\(x=1\)</span>.</p>
<hr>
</div>
</div>
<div id="resumen" class="section level2">
<h2>Resumen</h2>
<center>
<img src="IC_mu-mu.png" title="fig:" alt="Resumen IC" />
</center>
<p>Con:</p>
<p><span class="math display">\[SP=\sqrt{\cfrac{(n_1-1)S^2_1+(n_2-1)S^2_2}{n_1+n_2-2}}\]</span> y</p>
<p><span class="math display">\[\large v= \cfrac{\left(\frac{S^2_1}{n_1}+\frac{S^2_2}{n_2}\right)^2}{\frac{\left(\frac{S^2_1}{n_1}\right)^2}{n_1-1}+\frac{\left(\frac{S^2_2}{n_2}\right)^2}{n_2-1}}\]</span></p>
<hr>
</div>
<div id="ejemplo-práctico" class="section level2">
<h2>Ejemplo práctico</h2>
<p>La siguiente base de datos contiene información acerca de incautaciones de bebidas alcohólicas fraudulentas y de contrabando en la ciudad de Medellín en un mes, que afectan los recursos para Salud y Educación en el Departamento de Antioquia y de acuerdo a los resultados se toma decisiones para aumentar o disminuir los controles.</p>
<center>
<a href="./R/Licores.xlsx" class="btn btn-info" target="_blank">Licores</a>
</center>
<p><br></p>
<p>La base de datos contiene las variables - <strong>TL</strong> (Tipo de Licor) - <strong>PI</strong> (Precio de incautación: se refiere al precio de venta en el establecimiento por unidad) - <strong>GAE</strong> (Grados de Alcohol en etiqueta) - <strong>GAQ</strong> (grados de alcohol en prueba química) - <strong>CE</strong> (Cantidades estandarizadas: número de unidades estandarizadas a 750 ml).</p>
<p>Usando la información de su base de datos responda a las siguientes preguntas.</p>
<ol style="list-style-type: decimal">
<li><p>El <strong>precio total</strong> de la incautación se calcula como la cantidad estandarizada por el precio de incautación. ¿Se puede afirmar que el precio total promedio de la incautación es superior a $7’500.000?</p></li>
<li><p>El <strong>ipoconsumo</strong>, es el impuesto que deja de percibir el Estado para salud y educación, el cual se calcula como: <span class="math inline">\(GAQ \times CE \times 400\)</span> (pesos). ¿Se puede afirmar que el ipoconsumo promedio del ron es inferior al ipoconsumo medio del Whisky? ¿Qué decisión se puede tomar frente al control?</p></li>
<li><p>El licor incautado se clasifica como “Fraudulento” si los GAE son distintos a los GAQ y como “contrabando” si son iguales. ¿La proporción de licores fraudulentos es superior al 65%? ¿Qué significa éste resultado?</p></li>
<li><p>Se piensa que los ilegales mezclan el licor con otras sustancias para disminuir los grados de alcohol del licor. ¿Existe evidencia para este planteamiento?</p></li>
<li><p>De acuerdo con los datos, se sabe que el Aguardiente y el Tequila son los licores con más incautaciones. Desde el equipo de Rentas se sostiene que el Aguardiente es el licor que más se adultera. ¿Es correcta esta afirmación?</p></li>
</ol>
<hr>
<div id="solución-usando-r" class="section level3">
<h3>Solución usando R</h3>
<p>Lo primero es descargar la base de datos en la carpeta que se considere, luego debemos cargar la base de datos en <code>RStudio</code> para realizar los análisis. Antes de comenzar con el análisis necesitamos instalar o cargar las librerías necesarias para el análisis</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Para manipular datos</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(dplyr)) <span class="fu">install.packages</span>(<span class="st">&quot;dplyr&quot;</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráficos con estilo</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(ggplot2)) <span class="fu">install.packages</span>(<span class="st">&quot;ggplot2&quot;</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráficos QQ-plot con IC</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(car)) <span class="fu">install.packages</span>(<span class="st">&quot;car&quot;</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Importar/Exportar datos de Excel</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(openxlsx)) <span class="fu">install.packages</span>(<span class="st">&quot;openxlsx&quot;</span>)</span></code></pre></div>
<p>El siguiente paso es cargar la base de datos, esto lo podemos realizar directamente de <code>RStudio</code> con el siguiente comando:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>Licores <span class="ot">&lt;-</span> <span class="fu">read.xlsx</span>(<span class="fu">file.choose</span>(),<span class="at">sheet =</span> <span class="dv">1</span>)</span></code></pre></div>
<p>Revisemos la estructura de los datos, para verificar si fueron cargados correctamente.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Licores)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    300 obs. of  5 variables:
##  $ TL : chr  &quot;Ron&quot; &quot;Aguardiente&quot; &quot;Ron&quot; &quot;Aguardiente&quot; ...
##  $ PI : num  34719 26900 27062 29317 32471 ...
##  $ GAE: num  35 29 35 29 38 29 29 38 35 40 ...
##  $ GAQ: num  30.2 29 32.2 29 32.6 ...
##  $ CE : num  221 253 249 254 267 ...</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cambiando caracter por factor</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>Licores <span class="ot">&lt;-</span> Licores <span class="sc">%&gt;%</span> <span class="fu">mutate_if</span>(is.character,as.factor)</span></code></pre></div>
<p>El primer punto nos piden calcular <strong>el precio total</strong> de incautación, y se pregunta si el promedio de esa nueva variable es superior a 7.5 millones. Para seleccionar el estadístico de prueba más indicado, debemos probar si la distribución del precio total de incautación es Normal.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Licores<span class="sc">$</span>PT <span class="ot">&lt;-</span> Licores<span class="sc">$</span>CE<span class="sc">*</span>Licores<span class="sc">$</span>PI</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico en 3 partes</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># histograma + Densidad</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Licores<span class="sc">$</span>PT,<span class="at">freq=</span>F,<span class="at">col=</span><span class="st">&quot;lightblue&quot;</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(Licores<span class="sc">$</span>PT),<span class="at">main=</span><span class="st">&quot;Density Plot&quot;</span>,<span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Acumulada vs Teórica</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">ecdf</span>(Licores<span class="sc">$</span>PT),<span class="at">main=</span><span class="st">&quot;Cumulative Plot&quot;</span>,<span class="at">cex=</span><span class="dv">1</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">pnorm</span>(x,<span class="fu">mean</span>(Licores<span class="sc">$</span>PT),<span class="fu">sd</span>(Licores<span class="sc">$</span>PT)),<span class="at">add=</span>T,<span class="at">col=</span><span class="dv">5</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># QQ-Plot</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(Licores<span class="sc">$</span>PT,<span class="at">main =</span> <span class="st">&quot;QQ - Plot&quot;</span>,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">id=</span>F,<span class="at">cex=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="I_ic2_files/figure-html/unnamed-chunk-10-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>Entonces, siguiendo el árbol de decisión tenemos que los datos se distribuyen normal y no conocemos los parámetros poblacionales, por lo tanto el estadístico de prueba está basado en la <em>t-student</em>.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Licores<span class="sc">$</span>PT,<span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  Licores$PT
## t = 102.67, df = 299, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  7325868 7612193
## sample estimates:
## mean of x 
##   7469031</code></pre>
<p>Como el intervalo de confianza está compuesto por <span class="math inline">\((7&#39;325.868;\,7&#39;612.193)\)</span> y contiene el valor teórico de los 7.5 millones, existe evidencia muestral suficiente de que el promedio del precio de incautaciones mesual es de $7’500.000, esto implica anualmente se esperaría que alrededor de 90 millones de pesos deje de circular ilegalmente gracias a lo no pago de impuestos o adulteración de licores.</p>
<hr>
<p>En la siguiente pregunta se pide calcular el <em>ipoconsumo</em> de acuerdo a una formulación, y luego comparar si el impuesto de los licores de tipo <em>Ron</em> son menores a los de <em>Whisky</em> basado en los promedios.</p>
<p>De acuerdo al árbol de decisión tenemos que hacer los siguientes pasos:</p>
<ul>
<li>Calcular el ipoconsumo</li>
<li>Separar la base de datos en Ron y Whisky</li>
<li>Probar la normalidad de ambos grupos</li>
<li>Comprobar la igualdad de varianzas de los grupos</li>
<li>Escoger el mejor estadístico de prueba y realizar el análisis.</li>
<li>Concluir</li>
</ul>
<p>Los primeros dos pasos son sencillos:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Licores <span class="ot">&lt;-</span> Licores <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">IPO =</span> GAQ<span class="sc">*</span>CE<span class="sc">*</span><span class="dv">400</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Licores<span class="sc">$</span>IPO,<span class="at">col=</span><span class="st">&quot;lightblue&quot;</span>,<span class="at">las=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="I_ic2_files/figure-html/unnamed-chunk-12-1.png" width="630" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>SoloRW <span class="ot">&lt;-</span> Licores <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">filter</span>(TL <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Ron&quot;</span>,<span class="st">&quot;Whisky&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>   droplevels</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>SoloRW <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(TL) <span class="sc">%&gt;%</span> </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">summarise</span>(<span class="at">n=</span><span class="fu">length</span>(IPO),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">media=</span><span class="fu">mean</span>(IPO),</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">desv=</span><span class="fu">sd</span>(IPO))</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   TL         n    media    desv
## * &lt;fct&gt;  &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 Ron       52 3185673. 270971.
## 2 Whisky    27 3591694. 317110.</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>SoloRW <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>IPO,<span class="at">fill=</span>TL))<span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_density</span>(<span class="at">alpha=</span><span class="fl">0.5</span>)<span class="sc">+</span><span class="fu">xlim</span>(<span class="fu">c</span>(<span class="fl">2e06</span>,<span class="fl">5e06</span>))<span class="sc">+</span><span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="I_ic2_files/figure-html/unnamed-chunk-12-2.png" width="630" style="display: block; margin: auto;" /></p>
<p>Luego debemos probar la normalidad de los datos. Una opción es separar la base de datos y construir dos nuevas con los grupos de interés.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluar - Normalidad</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(SoloRW <span class="sc">%&gt;%</span> <span class="fu">filter</span>(TL<span class="sc">==</span><span class="st">&quot;Ron&quot;</span>),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">qqPlot</span>(IPO,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">main =</span> <span class="st">&quot;QQ-Plot Ron&quot;</span>,<span class="at">id=</span>F,<span class="at">col.lines =</span> <span class="dv">2</span>))</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(SoloRW <span class="sc">%&gt;%</span> <span class="fu">filter</span>(TL<span class="sc">==</span><span class="st">&quot;Whisky&quot;</span>),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>     <span class="fu">qqPlot</span>(IPO,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">main =</span> <span class="st">&quot;QQ-Plot Whisky&quot;</span>,<span class="at">id=</span>F,<span class="at">col.lines =</span> <span class="dv">4</span>))</span></code></pre></div>
<p><img src="I_ic2_files/figure-html/unnamed-chunk-13-1.png" width="630" style="display: block; margin: auto;" /></p>
<p>Como ambas muestras distribuyen normal, es necesario verificar si existe igualdad en sus varianzas, esto se comprueba con la función <code>var.test</code>.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(SoloRW,<span class="fu">var.test</span>(IPO<span class="sc">~</span>TL))</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  IPO by TL
## F = 0.73017, num df = 51, denom df = 26, p-value = 0.3333
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.3562148 1.3878542
## sample estimates:
## ratio of variances 
##           0.730172</code></pre>
<p>Entonces, como los datos son normales y tienen varianzas iguales, de acuerdo con el árbol de decisión el mejor estadístico de prueba está basado en la <em>t-student</em> y es necesario estimar la varianza conjunta, no obstante, el software lo hace:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(SoloRW,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">t.test</span>(IPO[TL<span class="sc">==</span><span class="st">&quot;Ron&quot;</span>],</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>            IPO[TL<span class="sc">==</span><span class="st">&quot;Whisky&quot;</span>],</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">var.equal =</span> T))</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  IPO[TL == &quot;Ron&quot;] and IPO[TL == &quot;Whisky&quot;]
## t = -5.9561, df = 77, p-value = 7.258e-08
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -541763.2 -270279.6
## sample estimates:
## mean of x mean of y 
##   3185673   3591694</code></pre>
<p>En conclusión, el ipoconsumo del ron es menor al del whisky ya que el IC al 95% no contiene el cero. Entonces la cantidad de impuestos que deja de percibir el departamento tiene mayor aporte en el Whisky, sin embargo, las cantidades de Ron son casi el doble que las de Whisky lo que sugiere que este licor es preferido para la adulteración. Los controles se deben aumentar para incautar más Ron y establecer una estrategia para que no aumente la adulteración del Whisky que es la que más afecta los recursos para salud.</p>
<hr>
<p>El tercer punto nos piden calcular una nueva variable, si <span class="math inline">\(GAQ=GAE\)</span> el licor se clasifica como <strong>contrabando</strong> en caso contrario se llamará <strong>fraudulento</strong>.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>Licores <span class="ot">&lt;-</span> Licores <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">Incautacion =</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(GAQ<span class="sc">==</span>GAE,<span class="st">&quot;Contrabando&quot;</span>,<span class="st">&quot;Fraudulento&quot;</span>)))</span></code></pre></div>
<p>Luego preguntan si la proporción de licores Fraudulentos es superior al 65%.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(Licores,<span class="fu">table</span>(Incautacion))</span></code></pre></div>
<pre><code>## Incautacion
## Contrabando Fraudulento 
##          83         217</code></pre>
<p>Como en <code>R</code> los factores se organizan alfabéticamente, entonces debemos cambiar la hipótesis hacia los licores de <strong>contrabando</strong>, entoces se evaluará si la proporción de licores de contrabando es del 35%.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(Licores,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">prop.test</span>(<span class="fu">table</span>(Incautacion),</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">correct =</span> F))</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  table(Incautacion), null probability 0.5
## X-squared = 59.853, df = 1, p-value = 1.022e-14
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.2291106 0.3298699
## sample estimates:
##         p 
## 0.2766667</code></pre>
<p>Como el intervalo está dado por <span class="math inline">\((22.91\%;\,32.99\%)\)</span> y el valor teórico está por fuera del rango, por lo tanto existe evidencia muestral para afirmar que la proporción de licores Fraudulentos es mayor del 65%. Por lo tanto, las rentas ilegales de licores están basadas en mayor medida de la adulteración, el impacto para la salud pública es muy grave, pues los efectos nocivos de los licores que no son correctamente destilados aumenta los riesgos clínicos como la ceguera, el cáncer de órganos digestivos o la muerte.</p>
<hr>
<p>Para el cuarto punto nos piden determinar si los grados de alchol son menores en los licores fraudulentos en comparación con los de contrabando, debido a que si los grados de alcohol disminuyen se va ver reflejado en la variable <span class="math inline">\(GAQ\)</span> y si los licores son de contrabando no se notará el cambio en los grados de alcohol.</p>
<p>Para responder esta pregunta debemos estimar un IC para la diferencia de medias, donde la variable cuantitativa es <code>GAQ</code> y la variable que agrupa es <code>Incautacion</code>. Entonces los pasos a seguir son:</p>
<ul>
<li>Verificar normalidad en ambos grupos.</li>
<li>Verificar tamaños de muestra si al menos uno no distribuye normal.</li>
<li>Verificar igualdad de varianzas si ambos distribuyen normal.</li>
<li>Seleccionar el estadístico de prueba.</li>
<li>Concluir.</li>
</ul>
<p>En <code>R</code> es sencillo realizar estos pasos. Primero, podemos realizar un resumen numérico de los datos.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>Licores <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Incautacion) <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n=</span><span class="fu">length</span>(GAQ),</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">media=</span><span class="fu">mean</span>(GAQ),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">desv=</span><span class="fu">sd</span>(GAQ))</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   Incautacion     n media  desv
## * &lt;fct&gt;       &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Contrabando    83  33.4  4.36
## 2 Fraudulento   217  29.8  3.88</code></pre>
<p>A primera vista se puede ver que las desvaciones estándar de ambos grupos son pequeñas con respecto al promedio, esto no es un indicio suficiente para analizar el comportamiento; lo podemos verificar con un gráfico.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Licores,<span class="fu">aes</span>(<span class="at">x=</span>GAQ,<span class="at">fill=</span>Incautacion))<span class="sc">+</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha=</span><span class="fl">0.5</span>)</span></code></pre></div>
<p><img src="I_ic2_files/figure-html/unnamed-chunk-20-1.png" width="630" style="display: block; margin: auto;" /></p>
<p>El comportamiento de cada grupo es bimodal, obviamente esta característica se contradice con una distribución normal, no obstante, se puede hacer la verificación con el QQ-Plot.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluar - Normalidad</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(Licores <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Incautacion<span class="sc">==</span><span class="st">&quot;Contrabando&quot;</span>),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">qqPlot</span>(GAQ,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">main =</span> <span class="st">&quot;QQ-Plot Contrabando&quot;</span>,<span class="at">id=</span>F,<span class="at">col.lines =</span> <span class="dv">2</span>))</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(Licores <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Incautacion<span class="sc">==</span><span class="st">&quot;Fraudulento&quot;</span>),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>     <span class="fu">qqPlot</span>(GAQ,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">main =</span> <span class="st">&quot;QQ-Plot Fraudulento&quot;</span>,<span class="at">id=</span>F,<span class="at">col.lines =</span> <span class="dv">4</span>))</span></code></pre></div>
<p><img src="I_ic2_files/figure-html/unnamed-chunk-21-1.png" width="630" style="display: block; margin: auto;" /></p>
<p>Como ambas muestras no distribuyen normal y los tamaños de muestra de ambos grupos son superiores a 30, podemos realizar el intervalo de confianza para la media, aproximando el resultado a una normal. En <code>R</code> existe un paquete para realizar estos intervalos, y al mismo tiempo verificar hipótesis, es muy similar al <code>t.test</code> la diferencia es que hay que especificarle los valores de las desviaciones estadándar de cada grupo. El paquete se llama <code>BSDA</code> y la función de interés es <code>z.test</code>.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;BSDA&quot;</span>,<span class="at">dependencies =</span> T)</span></code></pre></div>
<p>Para este ejercicio, sabemos que no contamos con información previa acerca de los datos, por lo tanto no conocemos las varianzas de los grados de alcohol por cada grupo, así que se debe utilizar las varianzas muestrales de cada uno.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(BSDA)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(Licores,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">z.test</span>(<span class="at">x =</span> GAQ[Incautacion<span class="sc">==</span><span class="st">&quot;Contrabando&quot;</span>],</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">y =</span> GAQ[Incautacion<span class="sc">==</span><span class="st">&quot;Fraudulento&quot;</span>],</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">sigma.x =</span> <span class="fu">sd</span>(GAQ[Incautacion<span class="sc">==</span><span class="st">&quot;Contrabando&quot;</span>]),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">sigma.y =</span> <span class="fu">sd</span>(GAQ[Incautacion<span class="sc">==</span><span class="st">&quot;Fraudulento&quot;</span>])))</span></code></pre></div>
<pre><code>## 
##  Two-sample z-Test
## 
## data:  GAQ[Incautacion == &quot;Contrabando&quot;] and GAQ[Incautacion == &quot;Fraudulento&quot;]
## z = 6.5525, p-value = 5.658e-11
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  2.507594 4.647927
## sample estimates:
## mean of x mean of y 
##  33.42169  29.84393</code></pre>
<p>En conclusión, los grados de alcohol de los licores Fraudulentos son menores a los de Contrabando, ya que el intervalo al 95% no contiene el cero y los límites son positivos. Entonces los ilegales que adulteran los licores, disminuyen significativamente los grados de alcohol, esto se explica porque los licores destilados contienen etanol que es más fácil de procesar para el hígado en comparación con el metanol que en su mayoría es utilizado para adulterar los licores, el cual produce envenenamiento. Si bien los grados de alcohol en los licores fraudulentos son menores, no significan que sean menos letales, debido a su composición química.</p>
<hr>
<p>La última pregunta nos piden realizar un intervalo de confianza para la diferencia de proporciones, ya que las dos variables seleccionadas son cualitativas <code>Incautacion</code> y <code>TL</code>. En <code>R</code> es fácil realizar este cálculo mediante la función <code>prop.test</code>, pero antes debemos seleccionar adecuandamente los datos y el orden de entrada en la función.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>Licores <span class="sc">%&gt;%</span> <span class="fu">select</span>(TL,Incautacion) <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  table</span></code></pre></div>
<pre><code>##              Incautacion
## TL            Contrabando Fraudulento
##   Aguardiente          39          86
##   Ron                  13          39
##   Tequila              26          70
##   Whisky                5          22</code></pre>
<p>La tabla se organiza por orden alfabético, además la tabla es de varios niveles, es decir, no es <span class="math inline">\(2\times2\)</span>. Una opción es reducir la tabla filtrando los datos, o la otra opción es ingresar los datos de interés a la función <code>prop.test</code>.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordenando las filas y columnas</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>Licores <span class="sc">%&gt;%</span> <span class="fu">select</span>(TL,Incautacion) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  table <span class="sc">%&gt;%</span> .[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">4</span>),<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>)]</span></code></pre></div>
<pre><code>##              Incautacion
## TL            Fraudulento Contrabando
##   Aguardiente          86          39
##   Tequila              70          26
##   Ron                  39          13
##   Whisky               22           5</code></pre>
<p>También podemos poner los totales marginales a la tabla, que son útiles para el paso final.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>Licores <span class="sc">%&gt;%</span> <span class="fu">select</span>(TL,Incautacion) <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  table <span class="sc">%&gt;%</span> .[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">4</span>),<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>)] <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  addmargins</span></code></pre></div>
<pre><code>##              Incautacion
## TL            Fraudulento Contrabando Sum
##   Aguardiente          86          39 125
##   Tequila              70          26  96
##   Ron                  39          13  52
##   Whisky               22           5  27
##   Sum                 217          83 300</code></pre>
<p>Finalmente, para construir el intervalo de confianza ingresamos los éxitos de cada grupo y los totales marginales de los mismos.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">86</span>,<span class="dv">70</span>),<span class="at">n =</span> <span class="fu">c</span>(<span class="dv">125</span>,<span class="dv">96</span>),<span class="at">correct =</span> T)</span></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  c(86, 70) out of c(125, 96)
## X-squared = 0.26712, df = 1, p-value = 0.6053
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.17078698  0.08845364
## sample estimates:
##    prop 1    prop 2 
## 0.6880000 0.7291667</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">86</span>,<span class="dv">70</span>),<span class="at">n =</span> <span class="fu">c</span>(<span class="dv">125</span>,<span class="dv">96</span>),<span class="at">correct =</span> F)</span></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions without continuity
##  correction
## 
## data:  c(86, 70) out of c(125, 96)
## X-squared = 0.44323, df = 1, p-value = 0.5056
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.16157864  0.07924531
## sample estimates:
##    prop 1    prop 2 
## 0.6880000 0.7291667</code></pre>
<p>En conclusión, como el intervalo de confianza al 95% contiene el cero, esto sugiere que no existe evidencia muestral suficiente para soportar el argumento de que el Aguardiente sea el licor que más se adultera en comparación con el Tequila. El equipo de Rentas no debe confiarse en los operativos de aprehensiones y realizar pruebas químicas a todos los licores incautados.</p>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
